<?xml version='1.0'  encoding='Cp1251' ?>
<RESULTS>
	<ROW>
		<COLUMN NAME="ORDER_NUM"><![CDATA[1]]></COLUMN>
		<COLUMN NAME="ORDER_DATE"><![CDATA[21-11-2019]]></COLUMN>
		<COLUMN NAME="PRODUCT"><![CDATA[CHAIR]]></COLUMN>
		<COLUMN NAME="AMOUNT"><![CDATA[200]]></COLUMN>
		<COLUMN NAME="TEXT"><![CDATA[]]></COLUMN>
		<COLUMN NAME="IMG"><![CDATA[(BLOB)]]></COLUMN>
		<COLUMN NAME="F_NAME"><![CDATA[]]></COLUMN>
		<COLUMN NAME="I_NAME"><![CDATA[]]></COLUMN>
	</ROW>
	<ROW>
		<COLUMN NAME="ORDER_NUM"><![CDATA[2]]></COLUMN>
		<COLUMN NAME="ORDER_DATE"><![CDATA[03-06-2017]]></COLUMN>
		<COLUMN NAME="PRODUCT"><![CDATA[TABLE]]></COLUMN>
		<COLUMN NAME="AMOUNT"><![CDATA[400]]></COLUMN>
		<COLUMN NAME="TEXT"><![CDATA[]]></COLUMN>
		<COLUMN NAME="IMG"><![CDATA[(BLOB)]]></COLUMN>
		<COLUMN NAME="F_NAME"><![CDATA[]]></COLUMN>
		<COLUMN NAME="I_NAME"><![CDATA[]]></COLUMN>
	</ROW>
	<ROW>
		<COLUMN NAME="ORDER_NUM"><![CDATA[3]]></COLUMN>
		<COLUMN NAME="ORDER_DATE"><![CDATA[10-11-2008]]></COLUMN>
		<COLUMN NAME="PRODUCT"><![CDATA[BED]]></COLUMN>
		<COLUMN NAME="AMOUNT"><![CDATA[100]]></COLUMN>
		<COLUMN NAME="TEXT"><![CDATA[Here's my favorite story on recursion: it happened that a famous Darwinist was
telling a story about primitive creation myths. "Some peoples," he said, "believe the
world rests on the back of a great turtle. Of course, that raises the question: on what
does the turtle rest?"
An elderly woman from the back of the room stood up and said, "Very clever,
Sonny, but it's turtles, all the way down."]]></COLUMN>
		<COLUMN NAME="IMG"><![CDATA[(BLOB)]]></COLUMN>
		<COLUMN NAME="F_NAME"><![CDATA[1.txt]]></COLUMN>
		<COLUMN NAME="I_NAME"><![CDATA[1.jpg]]></COLUMN>
	</ROW>
	<ROW>
		<COLUMN NAME="ORDER_NUM"><![CDATA[4]]></COLUMN>
		<COLUMN NAME="ORDER_DATE"><![CDATA[12-10-2017]]></COLUMN>
		<COLUMN NAME="PRODUCT"><![CDATA[BATH]]></COLUMN>
		<COLUMN NAME="AMOUNT"><![CDATA[140]]></COLUMN>
		<COLUMN NAME="TEXT"><![CDATA[]]></COLUMN>
		<COLUMN NAME="IMG"><![CDATA[(BLOB)]]></COLUMN>
		<COLUMN NAME="F_NAME"><![CDATA[]]></COLUMN>
		<COLUMN NAME="I_NAME"><![CDATA[]]></COLUMN>
	</ROW>
	<ROW>
		<COLUMN NAME="ORDER_NUM"><![CDATA[5]]></COLUMN>
		<COLUMN NAME="ORDER_DATE"><![CDATA[30-11-2016]]></COLUMN>
		<COLUMN NAME="PRODUCT"><![CDATA[CHANDELIER]]></COLUMN>
		<COLUMN NAME="AMOUNT"><![CDATA[160]]></COLUMN>
		<COLUMN NAME="TEXT"><![CDATA[]]></COLUMN>
		<COLUMN NAME="IMG"><![CDATA[(BLOB)]]></COLUMN>
		<COLUMN NAME="F_NAME"><![CDATA[]]></COLUMN>
		<COLUMN NAME="I_NAME"><![CDATA[]]></COLUMN>
	</ROW>
	<ROW>
		<COLUMN NAME="ORDER_NUM"><![CDATA[6]]></COLUMN>
		<COLUMN NAME="ORDER_DATE"><![CDATA[02-02-2015]]></COLUMN>
		<COLUMN NAME="PRODUCT"><![CDATA[LAMP]]></COLUMN>
		<COLUMN NAME="AMOUNT"><![CDATA[240]]></COLUMN>
		<COLUMN NAME="TEXT"><![CDATA[]]></COLUMN>
		<COLUMN NAME="IMG"><![CDATA[(BLOB)]]></COLUMN>
		<COLUMN NAME="F_NAME"><![CDATA[]]></COLUMN>
		<COLUMN NAME="I_NAME"><![CDATA[]]></COLUMN>
	</ROW>
	<ROW>
		<COLUMN NAME="ORDER_NUM"><![CDATA[7]]></COLUMN>
		<COLUMN NAME="ORDER_DATE"><![CDATA[17-11-2014]]></COLUMN>
		<COLUMN NAME="PRODUCT"><![CDATA[FIREPLACE]]></COLUMN>
		<COLUMN NAME="AMOUNT"><![CDATA[220]]></COLUMN>
		<COLUMN NAME="TEXT"><![CDATA[]]></COLUMN>
		<COLUMN NAME="IMG"><![CDATA[(BLOB)]]></COLUMN>
		<COLUMN NAME="F_NAME"><![CDATA[]]></COLUMN>
		<COLUMN NAME="I_NAME"><![CDATA[2.jpg]]></COLUMN>
	</ROW>
</RESULTS>